@extends('errors.layout')
@section('title', 'Страница не найдена')
@section('code', '404')
@section('message', 'Страница не найдена')
@section('description', 'Запрошенная вами страница была перемещена или удалена.')
