<?php

namespace App\Core\Support;

class SettingCatalog
{
    public static function groups(): array
    {
        return [
            'site' => [
                'label' => 'Основные',
                'description' => 'Базовые параметры сайта и публичного брендинга.',
                'fields' => [
                    'site.name' => ['label' => 'Название сайта', 'type' => 'string', 'input' => 'text', 'rules' => ['required', 'string', 'max:255'], 'description' => 'Отображается в заголовке страницы и шапке сайта'],
                    'site.url' => ['label' => 'URL сайта', 'type' => 'string', 'input' => 'url', 'rules' => ['required', 'url', 'max:500'], 'description' => 'Полный адрес вашего сайта, например: https://example.com'],
                    'site.description' => ['label' => 'Описание сайта', 'type' => 'string', 'input' => 'textarea', 'rules' => ['nullable', 'string', 'max:1000'], 'description' => 'Краткое описание для SEO и социальных сетей'],
                    'site.logo' => ['label' => 'Media ID логотипа', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID изображения из медиабиблиотеки, которое будет использоваться как логотип сайта'],
                    'site.favicon' => ['label' => 'Media ID favicon', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID иконки из медиабиблиотеки для отображения во вкладке браузера'],
                    'site.locale' => ['label' => 'Локаль сайта', 'type' => 'string', 'input' => 'text', 'rules' => ['required', 'string', 'max:20'], 'description' => 'Язык контента сайта, например: ru, en, de'],
                    'site.timezone' => ['label' => 'Часовой пояс', 'type' => 'string', 'input' => 'text', 'rules' => ['required', 'timezone'], 'description' => 'Временная зона для отображения дат, например: Europe/Moscow'],
                    'site.admin_locale' => ['label' => 'Язык админ-панели', 'type' => 'string', 'input' => 'select', 'options' => ['ru' => 'Русский', 'en' => 'English'], 'rules' => ['required', 'string', 'max:5'], 'description' => 'Язык интерфейса административной панели'],
                ],
            ],
            'design' => [
                'label' => 'Глобальный дизайн',
                'description' => 'Единая палитра, типографика, размеры контейнеров и кнопок для всех страниц.',
                'fields' => [
                    'design.primary_color' => ['label' => 'Основной цвет', 'type' => 'string', 'input' => 'color', 'rules' => ['nullable', 'regex:/^#[0-9a-fA-F]{6}$/'], 'description' => 'Основные кнопки, ссылки и акценты.'],
                    'design.secondary_color' => ['label' => 'Дополнительный цвет', 'type' => 'string', 'input' => 'color', 'rules' => ['nullable', 'regex:/^#[0-9a-fA-F]{6}$/'], 'description' => 'Вторичные элементы интерфейса.'],
                    'design.accent_color' => ['label' => 'Акцентный цвет', 'type' => 'string', 'input' => 'color', 'rules' => ['nullable', 'regex:/^#[0-9a-fA-F]{6}$/'], 'description' => 'Выделения и декоративные акценты.'],
                    'design.text_color' => ['label' => 'Цвет текста', 'type' => 'string', 'input' => 'color', 'rules' => ['nullable', 'regex:/^#[0-9a-fA-F]{6}$/']],
                    'design.background_color' => ['label' => 'Цвет фона', 'type' => 'string', 'input' => 'color', 'rules' => ['nullable', 'regex:/^#[0-9a-fA-F]{6}$/']],
                    'design.heading_font' => ['label' => 'Шрифт заголовков', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:80'], 'description' => 'Системный, загруженный или подключенный веб-шрифт.'],
                    'design.body_font' => ['label' => 'Шрифт текста', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:80']],
                    'design.base_font_size' => ['label' => 'Базовый размер текста, px', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:12', 'max:24']],
                    'design.content_width' => ['label' => 'Ширина контейнера, px', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:640', 'max:1920']],
                    'design.section_spacing' => ['label' => 'Вертикальный отступ секций, px', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:0', 'max:200']],
                    'design.button_radius' => ['label' => 'Скругление кнопок, px', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:0', 'max:100']],
                    'design.button_weight' => ['label' => 'Насыщенность кнопок', 'type' => 'integer', 'input' => 'select', 'options' => [400 => 'Обычная', 500 => 'Средняя', 600 => 'Полужирная', 700 => 'Жирная'], 'rules' => ['nullable', 'integer', 'in:400,500,600,700']],
                ],
            ],
            'seo' => [
                'label' => 'SEO',
                'description' => 'Глобальные SEO-настройки и поведение индексации.',
                'fields' => [
                    'seo.default_title' => ['label' => 'SEO title по умолчанию', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Заголовок страницы для поисковых систем, если не указан на конкретной странице'],
                    'seo.default_description' => ['label' => 'SEO description по умолчанию', 'type' => 'string', 'input' => 'textarea', 'rules' => ['nullable', 'string', 'max:500'], 'description' => 'Описание сайта для сниппета в поисковой выдаче'],
                    'seo.robots_enabled' => ['label' => 'Разрешить robots meta', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Добавлять meta-тег robots на страницы сайта'],
                    'seo.sitemap_enabled' => ['label' => 'Включить sitemap.xml', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Генерировать карту сайта для поисковых систем'],
                    'seo.organization_name' => ['label' => 'Название организации', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Официальное название организации для микроразметки Schema.org'],
                    'seo.organization_logo' => ['label' => 'Media ID логотипа организации', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID логотипа организации из медиабиблиотеки для микроразметки'],
                    'seo.robots_txt' => ['label' => 'Содержимое robots.txt', 'type' => 'string', 'input' => 'textarea', 'rules' => ['nullable', 'string', 'max:5000'], 'description' => 'Правила для поисковых роботов. Используйте User-agent для указания робота, Disallow для запрета индексации страниц, Allow для разрешения. Пример:\nUser-agent: *\nDisallow: /admin/\nAllow: /\nSitemap: https://yoursite.com/sitemap.xml'],
                ],
            ],
            'api' => [
                'label' => 'API и Mobile',
                'description' => 'Параметры публичного API для мобильных приложений и внешних клиентов.',
                'fields' => [
                    'api.public_enabled' => ['label' => 'Включить публичный API', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Разрешить доступ к публичному API для внешних клиентов'],
                    'api.mobile_enabled' => ['label' => 'Включить mobile API', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Разрешить доступ к API для мобильных приложений'],
                    'api.version' => ['label' => 'Версия API', 'type' => 'string', 'input' => 'text', 'rules' => ['required', 'string', 'max:20'], 'description' => 'Текущая версия API, например: v1, v2.1'],
                    'api.rate_limit_public' => ['label' => 'Public API rate limit', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:1'], 'description' => 'Максимальное количество запросов в минуту для публичного API (защита от перегрузки)'],
                    'api.rate_limit_mobile' => ['label' => 'Mobile API rate limit', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:1'], 'description' => 'Максимальное количество запросов в минуту для мобильного API'],
                ],
            ],
            'ai' => [
                'label' => 'AI',
                'description' => 'Провайдеры нейросетей, ключи и базовое поведение AI-помощника.',
                'fields' => [
                    'ai.enabled' => ['label' => 'Включить AI-модуль', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Активировать функции искусственного интеллекта на сайте'],
                    'ai.default_provider' => ['label' => 'Провайдер по умолчанию', 'type' => 'string', 'input' => 'select', 'options' => ['openai' => 'OpenAI', 'anthropic' => 'Anthropic', 'custom' => 'Custom'], 'rules' => ['nullable', 'string', 'max:50'], 'description' => 'Сервис ИИ, который будет использоваться по умолчанию'],
                    'ai.default_model' => ['label' => 'Модель по умолчанию', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:100'], 'description' => 'Конкретная модель ИИ, например: gpt-4, claude-3-opus'],
                    'ai.monthly_budget' => ['label' => 'Месячный бюджет', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:0'], 'description' => 'Лимит расходов на API запросы к ИИ в месяц (в рублях или долларах)'],
                    'ai.store_prompts' => ['label' => 'Хранить prompts', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Сохранять все отправленные запросы к ИИ в базе данных'],
                    'ai.store_responses' => ['label' => 'Хранить ответы', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Сохранять все полученные ответы от ИИ в базе данных'],
                    'ai.allow_editor_use' => ['label' => 'Разрешить Editor использовать AI', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Позволить пользователям с ролью Editor использовать AI-функции'],
                    'ai.content_language' => ['label' => 'Язык контента', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:20'], 'description' => 'Предпочтительный язык для генерации контента ИИ'],
                    'ai.brand_voice' => ['label' => 'Brand voice', 'type' => 'string', 'input' => 'textarea', 'rules' => ['nullable', 'string', 'max:2000'], 'description' => 'Инструкции по стилю общения: тон, формулировки, запрещённые слова. Например: «Пиши дружелюбно, используй простые предложения, избегай жаргона»'],
                    'ai.openai_api_key' => ['label' => 'OpenAI API key', 'type' => 'encrypted', 'input' => 'password', 'secret' => true, 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Секретный ключ доступа к API OpenAI. Получите на platform.openai.com'],
                    'ai.anthropic_api_key' => ['label' => 'Anthropic API key', 'type' => 'encrypted', 'input' => 'password', 'secret' => true, 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Секретный ключ доступа к API Anthropic. Получите на console.anthropic.com'],
                    'ai.custom_api_base' => ['label' => 'Custom API base URL', 'type' => 'string', 'input' => 'url', 'rules' => ['nullable', 'url', 'max:500'], 'description' => 'Адрес альтернативного API-сервера, совместимого с OpenAI форматом'],
                    'ai.custom_api_key' => ['label' => 'Custom API key', 'type' => 'encrypted', 'input' => 'password', 'secret' => true, 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Ключ доступа к кастомному API'],
                ],
            ],
            'pwa' => [
                'label' => 'PWA',
                'description' => 'Подготовка сайта к установке как progressive web app.',
                'fields' => [
                    'pwa.enabled' => ['label' => 'Включить PWA', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Разрешить установку сайта как приложения на устройство'],
                    'pwa.name' => ['label' => 'PWA name', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Полное название приложения, отображается при установке'],
                    'pwa.short_name' => ['label' => 'PWA short name', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:50'], 'description' => 'Короткое название для иконки на главном экране'],
                    'pwa.theme_color' => ['label' => 'Theme color', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:20'], 'description' => 'Цвет темы приложения (hex код), используется в строке состояния'],
                    'pwa.background_color' => ['label' => 'Background color', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:20'], 'description' => 'Цвет фона при загрузке приложения (hex код)'],
                    'pwa.display' => ['label' => 'Display mode', 'type' => 'string', 'input' => 'select', 'options' => ['standalone' => 'standalone', 'browser' => 'browser', 'minimal-ui' => 'minimal-ui'], 'rules' => ['nullable', 'string', 'max:30'], 'description' => 'Режим отображения: standalone — как приложение, browser — в браузере'],
                    'pwa.start_url' => ['label' => 'Start URL', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255'], 'description' => 'Страница, которая открывается при запуске приложения'],
                    'pwa.offline_page_id' => ['label' => 'Offline page ID', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID страницы, показываемой при отсутствии интернета'],
                    'pwa.icon_192' => ['label' => 'Media ID icon 192', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID иконки 192x192 пикселя из медиабиблиотеки'],
                    'pwa.icon_512' => ['label' => 'Media ID icon 512', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer'], 'description' => 'ID иконки 512x512 пикселя из медиабиблиотеки'],
                ],
            ],
            'cache' => [
                'label' => 'Кеш',
                'description' => 'Поведение кеша и базовые performance-параметры.',
                'fields' => [
                    'cache.enabled' => ['label' => 'Включить кеш', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Активировать кэширование страниц и данных'],
                    'cache.driver' => ['label' => 'Драйвер кеша', 'type' => 'string', 'input' => 'select', 'options' => ['file' => 'file', 'database' => 'database'], 'rules' => ['required', 'string', 'max:30'], 'description' => 'Место хранения кэша: file — файлы на сервере, database — таблица в БД'],
                    'cache.ttl' => ['label' => 'TTL в секундах', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:0'], 'description' => 'Время жизни кэша (Time To Live). Сколько секунд хранить данные до обновления. 0 — хранить бессрочно'],
                    'cache.html_minify' => ['label' => 'Минификация HTML', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Удалять лишние пробелы и комментарии из HTML для ускорения загрузки'],
                ],
            ],
            'maintenance' => [
                'label' => 'Режим обслуживания',
                'description' => 'Настройка страницы режима обслуживания и его поведения.',
                'fields' => [
                    'maintenance.enabled' => [
                        'label' => 'Включить режим обслуживания',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'maintenance.theme' => [
                        'label' => 'Тема оформления',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'minimal' => 'Minimal (Минимализм)',
                            'dark' => 'Dark (Тёмная)',
                            'light' => 'Light (Светлая)',
                            'gradient' => 'Gradient (Градиент)',
                            'geometric' => 'Geometric (Геометрия)',
                            'nature' => 'Nature (Природа)',
                            'city' => 'City (Город)',
                            'abstract' => 'Abstract (Абстракция)',
                            'retro' => 'Retro (Ретро)',
                            'tech' => 'Tech (Технологии)',
                        ],
                        'rules' => ['required', 'string', 'max:50'],
                    ],
                    'maintenance.background_image' => [
                        'label' => 'Media ID фонового изображения',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer'],
                    ],
                    'maintenance.background_blur' => [
                        'label' => 'Включить размытие фона',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'maintenance.logo' => [
                        'label' => 'Media ID логотипа',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer'],
                    ],
                    'maintenance.primary_color' => [
                        'label' => 'Основной цвет',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:20'],
                    ],
                    'maintenance.secondary_color' => [
                        'label' => 'Вторичный цвет',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:20'],
                    ],
                    'maintenance.title' => [
                        'label' => 'Заголовок',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                    ],
                    'maintenance.slogan' => [
                        'label' => 'Слоган',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:500'],
                    ],
                    'maintenance.text' => [
                        'label' => 'Описание',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string', 'max:2000'],
                    ],
                    'maintenance.show_login_form' => [
                        'label' => 'Показывать форму входа',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'maintenance.google_analytics_id' => [
                        'label' => 'Google Analytics ID',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                    ],
                    'maintenance.excluded_pages' => [
                        'label' => 'Исключить страницы из обслуживания',
                        'type' => 'json',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string', 'json'],
                        'description' => 'Массив путей в JSON формате, например: ["admin*", "api/*"]. Поддерживает wildcards.',
                    ],
                    'maintenance.cache_compatibility' => [
                        'label' => 'Режим совместимости с кэшем',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Добавляет заголовки для совместимости с плагинами кэширования',
                    ],
                    'maintenance.http_status_code' => [
                        'label' => 'HTTP статус код',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            '503' => '503 Service Unavailable',
                            '200' => '200 OK',
                            '302' => '302 Found',
                        ],
                        'rules' => ['required', 'string', 'in:503,200,302'],
                    ],
                    'maintenance.allowed_ips' => [
                        'label' => 'Разрешенные IP (по одному на строке)',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string'],
                        'description' => 'Эти IP обойдут режим обслуживания',
                    ],
                    'maintenance.bypass_for_admins' => [
                        'label' => 'Обход для администраторов',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                ],
            ],
            'mail' => [
                'label' => 'Почта (SMTP)',
                'description' => 'Настройка почтового сервера, шаблонов и параметров отправки.',
                'fields' => [
                    'mail.driver' => [
                        'label' => 'Драйвер',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'smtp' => 'SMTP',
                            'sendmail' => 'Sendmail',
                            'mailgun' => 'Mailgun',
                            'ses' => 'Amazon SES',
                            'postmark' => 'Postmark',
                            'log' => 'Лог (отладка)',
                        ],
                        'rules' => ['required', 'string', 'max:50'],
                    ],
                    'mail.host' => ['label' => 'SMTP хост', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255']],
                    'mail.port' => ['label' => 'SMTP порт', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:10'], 'description' => 'Обычно 25, 465 (SSL) или 587 (TLS)'],
                    'mail.encryption' => ['label' => 'Шифрование', 'type' => 'string', 'input' => 'select', 'options' => ['' => 'Нет', 'tls' => 'TLS', 'ssl' => 'SSL'], 'rules' => ['nullable', 'string', 'max:10']],
                    'mail.username' => ['label' => 'SMTP логин', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255']],
                    'mail.password' => ['label' => 'SMTP пароль', 'type' => 'string', 'input' => 'password', 'rules' => ['nullable', 'string', 'max:255'], 'secret' => true],
                    'mail.from_address' => ['label' => 'Адрес отправителя', 'type' => 'string', 'input' => 'email', 'rules' => ['nullable', 'email', 'max:255']],
                    'mail.from_name' => ['label' => 'Имя отправителя', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255']],
                    'mail.reply_to_address' => ['label' => 'Reply-To адрес', 'type' => 'string', 'input' => 'email', 'rules' => ['nullable', 'email', 'max:255']],
                    'mail.reply_to_name' => ['label' => 'Reply-To имя', 'type' => 'string', 'input' => 'text', 'rules' => ['nullable', 'string', 'max:255']],
                    'mail.test_recipient' => ['label' => 'Тестовый email', 'type' => 'string', 'input' => 'email', 'rules' => ['nullable', 'email', 'max:255'], 'description' => 'Адрес для тестовой отправки'],
                    'mail.queue_enabled' => ['label' => 'Использовать очередь', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Откладывать отправку в очередь mailer queue'],
                    'mail.retry_attempts' => ['label' => 'Попытки при ошибке', 'type' => 'integer', 'input' => 'number', 'rules' => ['nullable', 'integer', 'min:1', 'max:10'], 'description' => 'Сколько раз повторить при ошибке отправки'],
                    'mail.log_all' => ['label' => 'Логировать все письма', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Сохранять копию каждого письма в базе'],
                    'mail.attach_assets' => ['label' => 'Встраивать вложения', 'type' => 'boolean', 'input' => 'checkbox', 'rules' => ['nullable', 'boolean'], 'description' => 'Автоматически встраивать изображения из body'],
                ],
            ],
            'telegram' => [
                'label' => 'Telegram',
                'description' => 'Виджет чата Telegram для поддержки пользователей.',
                'fields' => [
                    'telegram.enabled' => [
                        'label' => 'Включить виджет',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'telegram.username' => [
                        'label' => 'Telegram username (без @)',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                        'description' => 'Например: mycompany_support',
                    ],
                    'telegram.bot_token' => [
                        'label' => 'Bot Token (опционально)',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:100'],
                        'secret' => true,
                        'description' => 'Если заполнено, можно отправлять сообщения через бота',
                    ],
                    'telegram.chat_id' => [
                        'label' => 'Chat/User ID (опционально)',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:100'],
                        'description' => 'ID чата или пользователя для получения сообщений',
                    ],
                    'telegram.widget_style' => [
                        'label' => 'Стиль виджета',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'button' => 'Кнопка',
                            'badge' => 'Круглая иконка с счётчиком',
                            'floating' => 'Плавающая кнопка',
                            'inline' => 'Вшитый в страницу',
                        ],
                        'rules' => ['required', 'string', 'max:20'],
                    ],
                    'telegram.widget_position' => [
                        'label' => 'Позиция (для плавающего)',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'bottom-right' => 'Справа снизу',
                            'bottom-left' => 'Слева снизу',
                            'bottom-center' => 'По центру снизу',
                        ],
                        'rules' => ['nullable', 'string', 'max:20'],
                    ],
                    'telegram.greeting' => [
                        'label' => 'Приветственный текст',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                        'description' => 'Текст в тултипе или рядом с кнопкой',
                    ],
                    'telegram.color' => [
                        'label' => 'Цвет кнопки (CSS)',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:20'],
                        'description' => 'Например: #0088cc или blue-500',
                    ],
                    'telegram.show_online_status' => [
                        'label' => 'Показывать статус онлайн',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'telegram.message_prefill' => [
                        'label' => 'Текст сообщения по умолчанию',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string', 'max:500'],
                        'description' => 'Текст, который подставится при открытии чата',
                    ],
                ],
            ],
            'forms' => [
                'label' => 'Формы и калькуляторы',
                'description' => 'Настройка действий форм, уведомлений, анти-спама и стилей.',
                'fields' => [
                    'forms.default_theme' => [
                        'label' => 'Тема форм по умолчанию',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'default' => 'Стандартная',
                            'minimal' => 'Минимализм',
                            'modern' => 'Современная',
                            'rounded' => 'Скруглённая',
                        ],
                        'rules' => ['nullable', 'string', 'max:50'],
                    ],
                    'forms.require_email_verification' => [
                        'label' => 'Требовать подтверждение email',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Отправлять письмо с ссылкой для подтверждения',
                    ],
                    'forms.honeypot_enabled' => [
                        'label' => 'Включить honeypot (защита от спама)',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.recaptcha_enabled' => [
                        'label' => 'Включить reCAPTCHA',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.recaptcha_site_key' => [
                        'label' => 'reCAPTCHA Site Key',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                    ],
                    'forms.recaptcha_secret_key' => [
                        'label' => 'reCAPTCHA Secret Key',
                        'type' => 'string',
                        'input' => 'password',
                        'rules' => ['nullable', 'string', 'max:255'],
                        'secret' => true,
                    ],
                    'forms.recaptcha_version' => [
                        'label' => 'reCAPTCHA версия',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'v2' => 'reCAPTCHA v2 (Я не робот)',
                            'v3' => 'reCAPTCHA v3 (невидимая)',
                        ],
                        'rules' => ['nullable', 'string', 'max:10'],
                    ],
                    'forms.notify_admin' => [
                        'label' => 'Уведомлять администратора',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.admin_emails' => [
                        'label' => 'Email админа для уведомлений',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string'],
                        'description' => 'Можно указать несколько, по одному на строке',
                    ],
                    'forms.notify_user' => [
                        'label' => 'Отправлять подтверждение пользователю',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.user_email_template' => [
                        'label' => 'Шаблон письма пользователю',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:100'],
                        'description' => 'Ключ шаблона из email_templates (например, form_confirmation)',
                    ],
                    'forms.autoresponder_subject' => [
                        'label' => 'Тема автоответа',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                    ],
                    'forms.autoresponder_body' => [
                        'label' => 'Тело автоответа (текст)',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string'],
                        'description' => 'Поддерживает merge tags: {field_name}, {form_name}, {site_name}',
                    ],
                    'forms.allow_duplicate' => [
                        'label' => 'Разрешить дубликаты отправок',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.max_entries' => [
                        'label' => 'Максимум отправок (всего)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:0'],
                    ],
                    'forms.daily_limit_per_ip' => [
                        'label' => 'Лимит отправок в день с одного IP',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:0'],
                    ],
                    'forms.show_entry_count' => [
                        'label' => 'Показывать количество отправок',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                    ],
                    'forms.custom_css' => [
                        'label' => 'Кастомный CSS',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string'],
                        'description' => 'Дополнительные стили для формы',
                    ],
                ],
            ],
            'security' => [
                'label' => 'Безопасность',
                'description' => 'Настройки CSRF, XSS, CSP, сессий и защиты от брутфорса.',
                'fields' => [
                    'security.csrf_enabled' => [
                        'label' => 'CSRF защита',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Включить CSRF токены для всех форм',
                    ],
                    'security.xss_protection' => [
                        'label' => 'XSS фильтрация',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Автоматическая санитизация пользовательского ввода',
                    ],
                    'security.content_security_policy' => [
                        'label' => 'Content Security Policy (CSP)',
                        'type' => 'string',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'string'],
                        'description' => "Заголовок CSP, например: default-src 'self'; script-src 'self' 'unsafe-inline'",
                    ],
                    'security.session_lifetime' => [
                        'label' => 'Время жизни сессии (минут)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:1'],
                        'default' => 120,
                    ],
                    'security.max_login_attempts' => [
                        'label' => 'Максимум попыток входа',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:1'],
                        'default' => 5,
                        'description' => 'После чего аккаунт блокируется',
                    ],
                    'security.lockout_time' => [
                        'label' => 'Время блокировки (минут)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:1'],
                        'default' => 10,
                        'description' => 'Время блокировки после превышения попыток входа',
                    ],
                    'security.password_min_length' => [
                        'label' => 'Мин. длина пароля',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:6'],
                        'default' => 8,
                    ],
                    'security.require_mfa' => [
                        'label' => 'Требовать 2FA для админов',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Обязательная двухфакторная аутентификация для ролей admin/super_admin',
                    ],
                ],
            ],
            'performance' => [
                'label' => 'Производительность и CDN',
                'description' => 'Настройки CDN, кэширования ассетов, lazy load и оптимизации загрузки.',
                'fields' => [
                    'performance.cdn_enabled' => [
                        'label' => 'Включить CDN',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Использовать CDN для доставки статических ресурсов',
                    ],
                    'performance.cdn_url' => [
                        'label' => 'CDN URL',
                        'type' => 'string',
                        'input' => 'url',
                        'rules' => ['nullable', 'url', 'max:500'],
                        'description' => 'Базовый URL CDN, например: https://cdn.example.com',
                    ],
                    'performance.asset_version' => [
                        'label' => 'Версия ассетов',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                        'description' => 'Версия для cache busting (автоматически при деплое)',
                    ],
                    'performance.lazy_load_images' => [
                        'label' => 'Lazy load изображений',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Отложенная загрузка изображений ниже viewport',
                    ],
                    'performance.preload_critical' => [
                        'label' => 'Preload критических ресурсов',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Предзагрузка критических CSS/шрифтов',
                    ],
                    'performance.http2_push' => [
                        'label' => 'HTTP/2 Push',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Server push для критических ассетов (требуется поддержка сервера)',
                    ],
                    'performance.minify_css' => [
                        'label' => 'Минификация CSS',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                    ],
                    'performance.minify_js' => [
                        'label' => 'Минификация JavaScript',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                    ],
                    'performance.gzip_compression' => [
                        'label' => 'Gzip сжатие',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Сжатие текстовых ресурсов (HTML, CSS, JS)',
                    ],
                    'performance.brotli_compression' => [
                        'label' => 'Brotli сжатие',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'description' => 'Более эффективное сжатие (приоритет над Gzip)',
                    ],
                ],
            ],
            'analytics' => [
                'label' => 'Аналитика и метрики',
                'description' => 'Интеграция с системами веб-аналитики: Google Analytics, Яндекс.Метрика, Hotjar.',
                'fields' => [
                    'analytics.google_analytics_id' => [
                        'label' => 'Google Analytics 4 Measurement ID',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                        'description' => 'Формат: G-XXXXXXXXXX',
                    ],
                    'analytics.yandex_metrika_id' => [
                        'label' => 'Яндекс.Метрика ID',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                        'description' => 'Номер счётчика, например: 12345678',
                    ],
                    'analytics.hotjar_id' => [
                        'label' => 'Hotjar Site ID',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                        'description' => 'ID сайта в Hotjar для heatmaps и записей сессий',
                    ],
                    'analytics.facebook_pixel_id' => [
                        'label' => 'Facebook Pixel ID',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                        'description' => 'ID пикселя Facebook для отслеживания конверсий',
                    ],
                    'analytics.enable_anonymous_tracking' => [
                        'label' => 'Анонимное отслеживание',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Не собирать персональные данные пользователей (GDPR compliance)',
                    ],
                    'analytics.respect_dnt' => [
                        'label' => 'Уважать Do Not Track',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Не отслеживать пользователей с включённым DNT в браузере',
                    ],
                    'analytics.cookie_consent_required' => [
                        'label' => 'Требуется согласие на cookies',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Показывать баннер согласия перед загрузкой трекеров',
                    ],
                ],
            ],
            'media' => [
                'label' => 'Медиа и файлы',
                'description' => 'Настройки загрузки файлов, генерации превью, сжатия изображений и форматов.',
                'fields' => [
                    'media.max_upload_size' => [
                        'label' => 'Макс. размер файла (MB)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:1'],
                        'default' => 10,
                        'description' => 'Максимальный размер загружаемого файла в мегабайтах',
                    ],
                    'media.allowed_extensions' => [
                        'label' => 'Разрешённые расширения (JSON)',
                        'type' => 'json',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'json'],
                        'default' => '["jpg","jpeg","png","gif","webp","svg","pdf","doc","docx","xls","xlsx"]',
                        'description' => 'Массив разрешённых расширений файлов в JSON формате',
                    ],
                    'media.image_quality' => [
                        'label' => 'Качество сжатия JPEG (%)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:10', 'max:100'],
                        'default' => 85,
                    ],
                    'media.generate_thumbnails' => [
                        'label' => 'Генерировать превью',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                    ],
                    'media.thumbnail_sizes' => [
                        'label' => 'Размеры превью (JSON)',
                        'type' => 'json',
                        'input' => 'textarea',
                        'rules' => ['nullable', 'json'],
                        'default' => '{"thumb":"150x150","small":"300x300","medium":"600x600","large":"1200x1200"}',
                        'description' => 'Объект размеров превью: {"name":"WxH", ...}',
                    ],
                    'media.use_webp' => [
                        'label' => 'Конвертировать в WebP',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Автоматическая конвертация PNG/JPEG в WebP для современных браузеров',
                    ],
                    'media.webp_quality' => [
                        'label' => 'Качество WebP (%)',
                        'type' => 'integer',
                        'input' => 'number',
                        'rules' => ['nullable', 'integer', 'min:10', 'max:100'],
                        'default' => 80,
                    ],
                    'media.strip_exif' => [
                        'label' => 'Удалять EXIF данные',
                        'type' => 'boolean',
                        'input' => 'checkbox',
                        'rules' => ['nullable', 'boolean'],
                        'default' => true,
                        'description' => 'Удаление метаданных из изображений для экономии места',
                    ],
                    'media.storage_driver' => [
                        'label' => 'Драйвер хранилища',
                        'type' => 'string',
                        'input' => 'select',
                        'options' => [
                            'local' => 'Локальное хранилище',
                            's3' => 'Amazon S3',
                            'spaces' => 'DigitalOcean Spaces',
                            'gcs' => 'Google Cloud Storage',
                        ],
                        'rules' => ['nullable', 'string', 'max:30'],
                        'default' => 'local',
                    ],
                    'media.s3_bucket' => [
                        'label' => 'S3 Bucket name',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:255'],
                    ],
                    'media.s3_region' => [
                        'label' => 'S3 Region',
                        'type' => 'string',
                        'input' => 'text',
                        'rules' => ['nullable', 'string', 'max:50'],
                    ],
                    'media.s3_access_key' => [
                        'label' => 'S3 Access Key',
                        'type' => 'string',
                        'input' => 'password',
                        'rules' => ['nullable', 'string', 'max:255'],
                        'secret' => true,
                    ],
                    'media.s3_secret_key' => [
                        'label' => 'S3 Secret Key',
                        'type' => 'string',
                        'input' => 'password',
                        'rules' => ['nullable', 'string', 'max:255'],
                        'secret' => true,
                    ],
                ],
            ],
        ];
    }

    public static function definitions(): array
    {
        return collect(self::groups())
            ->pluck('fields')
            ->collapse()
            ->all();
    }

    public static function definition(string $key): ?array
    {
        return self::definitions()[$key] ?? null;
    }

    public static function publicSiteKeys(): array
    {
        return [
            'site.name',
            'site.url',
            'site.description',
            'site.locale',
            'seo.default_title',
            'seo.default_description',
            'api.public_enabled',
            'api.mobile_enabled',
            'api.version',
            'pwa.enabled',
            'pwa.name',
            'pwa.short_name',
            'pwa.theme_color',
            'pwa.background_color',
            'pwa.display',
            'pwa.start_url',
        ];
    }

    public static function secretKeys(): array
    {
        return collect(self::definitions())
            ->filter(fn (array $definition) => (bool) ($definition['secret'] ?? false))
            ->keys()
            ->all();
    }
}
